x-common: &common
  restart: 'always'
  env_file:
    - .env
    - .env.local
  networks:
    - shoplist_network

services:
  web:
    build: .
    <<: *common
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      - 'sh'
      - '-c'
      - |
          python manage.py migrate --noinput &&
          gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./volumes/app:/app/static

  db:
    image: postgres:16
    <<: *common
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

networks:
  shoplist_network: