[project]
name = "shoplist"
version = "0.1.0"
description = "Small selfhost shopping list web app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-environ>=0.12.1",
    "gunicorn>=25.1.0",
    "psycopg[binary]>=3.3.2",
    "whitenoise>=6.11.0",
]
